version: "3.0"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "127.0.0.1:80:7092"
    expose:
      - 80
    networks: 
      - cool-app
    restart: always
  db:
    hostname: database_host
    image: postgres:latest
    environment:
      POSTGRES_DB: "movie_service"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "cvsecure"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - cool-app
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d movie_service" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
#322 7405
networks:
  cool-app: